name = "IterGP"
uuid = "4fe42191-a6bf-4090-968b-a1b7f610586b"
authors = ["Sebastian Callh <sebastian.callh@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
